spring:
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris: ${ELASTICSEARCH_URI}
  jpa:
    hibernate:
      ddl-auto: update
cloud:
  aws:
    region: ${AWS_REGION}
    s3:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY_ID}
      bucket-name: ${BUCKET_NAME}