spring:
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:config/ai.yml
      - classpath:config/security.yml
      - classpath:config/mail.yml
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # 프로젝트 실행 시 자동으로 배치 실행되게 하고 싶으면 true로 변경
#
cloud:
  aws:
    region: ${AWS_REGION}
    s3:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY_ID}
      bucket-name: ${BUCKET_NAME}
api:
  service-key: ${SERVICE_KEY}
data:
  elasticsearch:
    schema-management:
      create-index: false
      create-mappings: false
api-url:
  adoption: ${ADOPTION_URL}
  shelter: ${SHELTER_URL}