# repository clone 방식

on:
  push:
    branches:
      - feature/#13

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: feature/#13

      - name: Deploy to Cloud Instance
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          # 호스트 키 검증을 건너뛰려면 다음 줄 주석 해제
          # strict: false
          script: |
            set -e
            cd /home/ubuntu/final-pawong-backend
            
            git fetch origin feature/#13
            git reset --hard origin/feature/#13
            
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
